import mysql.connector as cnt
import tkinter
from PIL import Image, ImageTk
#database
ct=cnt.connect(user="root",host='localhost',password='yourpassword',database='blackpink')
cus=ct.cursor()
#gui
root=tkinter.Tk()
root.title("MAIN MENU")
root.geometry("1000x1000")
root.configure(bg='black')
image= Image.open("download.jpg")
photo=ImageTk.PhotoImage(image)
logo=tkinter.Label(root,image=photo,bg='black')
logo.pack()
i0=Image.open("doctor.png")
i0 =i0.resize((150, 150), Image.ANTIALIAS)
im0=ImageTk.PhotoImage(i0)
logos=tkinter.Label(root,image=im0,bg='black')
logos.pack()
logos.place(x='500',y='300')
i00=Image.open("Kundalini.png")
i00=i00.resize((250, 250), Image.ANTIALIAS)
im00=ImageTk.PhotoImage(i00)
logod=tkinter.Label(root,image=im00,bg='black')
logod.pack()
logod.place(x='700',y='300')
#staff adder
def adstaff():
    rot=tkinter.Toplevel(root)
    rot.title("Register Staff")
    rot.geometry("1000x1000")
    rot.configure(bg='black')
    logo=tkinter.Label(rot,image=photo)
    logo.pack()
    def fie():
        rot.destroy()
    a=tkinter.Label(rot,text="Enter ID: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='280')
    b=tkinter.Label(rot,text="Enter NAME: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='320')
    c=tkinter.Label(rot,text="Enter Experience: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='360')
    d=tkinter.Label(rot,text="Enter Department: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='400')
    e=tkinter.Label(rot,text="Enter Salary: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='440')
    f=tkinter.Label(rot,text="Enter Role: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='480')
    g=tkinter.Label(rot,text="Enter Ph.Number: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='520')
    h=tkinter.Label(rot,text="Enter Address: ", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='560')
    hi=tkinter.Button(rot,text="Back",bg='green',fg='white',bd='25',command=fie).place(x='700',y='600')
    ae=tkinter.Entry(rot,font=("16"))
    be=tkinter.Entry(rot,font=("16"))
    ce=tkinter.Entry(rot,font=("16"))
    de=tkinter.Entry(rot,font=("16"))
    ee=tkinter.Entry(rot,font=("16"))
    fe=tkinter.Entry(rot,font=("16"))
    ge=tkinter.Entry(rot,font=("16"))
    he=tkinter.Entry(rot,font=("16"))
    ae.pack()
    ae.place(x='505',y='280')
    be.pack()
    be.place(x='505',y='320')
    ce.pack()
    ce.place(x='505',y='360')
    de.pack()
    de.place(x='505',y='400')
    ee.pack()
    ee.place(x='505',y='440')
    fe.pack()
    fe.place(x='505',y='480')
    ge.pack()
    ge.place(x='505',y='520')
    he.pack()
    he.place(x='505',y='560')
    def st():
        x=ae.get()
        y=be.get()
        z=ce.get()
        za=de.get()
        zb=ee.get()
        zc=fe.get()
        zd=ge.get()
        ze=he.get()
        zas=0
        zad=0
        xa=(x,y,z,za,zb,zc,zd,ze,zas,zad)
        z="INSERT INTO stf VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)"
        cus.execute(z,xa)
        ct.commit()
        lb=tkinter.Label(rot,text="Added !!!")
        lb.pack()
        lb.place(x='505',y='660')
    bt=tkinter.Button(rot,text="Add",font=("Helvetica","16"),fg='white',bg='blue',bd='25', command=st).place(x='180',y='600')
    rot.mainloop()
#data retrieval  
def wdata():
    rot=tkinter.Toplevel(root)
    rot.title("Staff Details")
    rot.geometry("1000x1500")
    rot.configure(bg='black')
    logo=tkinter.Label(rot,image=photo,bg='black')
    logo.pack()
    def fie():
        rot.destroy()
    a=tkinter.Label(rot,text="Enter ID:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='280')
    ae=tkinter.Entry(rot,font=("16"))
    b=tkinter.Label(rot,text="Name:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='320')
    c=tkinter.Label(rot,text="Experience(in years):", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='360')
    d=tkinter.Label(rot,text="Department:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='400')
    e=tkinter.Label(rot,text="Salary:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='440')
    f=tkinter.Label(rot,text="Role", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='480')
    g=tkinter.Label(rot,text="Phone Number:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='520')
    h=tkinter.Label(rot,text="Address:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='560')
    i=tkinter.Label(rot,text="Appointment:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='600')
    j=tkinter.Label(rot,text="Tappt:", font=("Helvetica","16"),bg='black',fg='white').place(x='135',y='640')
    hi=tkinter.Button(rot,text="Back",bg='green',fg='white',bd='25',command=fie).place(x='100',y='100')
    ae.pack()
    ae.place(x='505',y='280')
    def alg():
        a=ae.get()
        ex=("SELECT * FROM stf WHERE id="+a)
        cus.execute(ex)
        vv=cus.fetchall()
        xcv=vv[0]
        bbb=1
        adder=0
        for i in range(len(xcv)-1):
            added=320+adder
            strr=(str(xcv[bbb])+'        ')
            al=tkinter.Label(rot,font=('20'),fg='white',bg='black',text=strr)
            al.pack()
            al.place(x='505',y=added)
            adder=adder+40
            bbb=bbb+1
    def changer():
        be=tkinter.Entry(rot,font=("16"))
        ce=tkinter.Entry(rot,font=("16"))
        de=tkinter.Entry(rot,font=("16"))
        ee=tkinter.Entry(rot,font=("16"))
        fe=tkinter.Entry(rot,font=("16"))
        ge=tkinter.Entry(rot,font=("16"))
        he=tkinter.Entry(rot,font=("16"))
        be.pack()
        be.place(x='760',y='320')
        ce.pack()
        ce.place(x='760',y='360')
        de.pack()
        de.place(x='760',y='400')
        ee.pack()
        ee.place(x='760',y='440')
        fe.pack()
        fe.place(x='760',y='480')
        ge.pack()
        ge.place(x='760',y='520')
        he.pack()
        he.place(x='760',y='560')
        def namechange():
            ax=str(ae.get())
            bx=str(be.get())
            sql=("UPDATE stf SET name=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        def expchange():
            ax=str(ae.get())
            bx=str(ce.get())
            sql=("UPDATE stf SET experience=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        def deptchange():
            ax=str(ae.get())
            bx=str(de.get())
            sql=("UPDATE stf SET dept=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        def salarychange():
            ax=str(ae.get())
            bx=str(ee.get())
            sql=("UPDATE stf SET salary=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        def rolechange():
            ax=str(ae.get())
            bx=str(fe.get())
            sql=("UPDATE stf SET role=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        def phnchange():
            ax=str(ae.get())
            bx=str(ge.get())
            sql=("UPDATE stf SET phn=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        def adrschange():
            ax=str(ae.get())
            bx=str(he.get())
            sql=("UPDATE stf SET adrs=%s WHERE id= %s")
            bbb=(bx,ax)
            cus.execute(sql,bbb)
            ct.commit()
        bt=tkinter.Button(rot,text='Change',command=namechange).place(x='950',y='320')
        bt=tkinter.Button(rot,text='Change',command=expchange).place(x='950',y='360')
        bt=tkinter.Button(rot,text='Change',command=deptchange).place(x='950',y='400')
        bt=tkinter.Button(rot,text='Change',command=salarychange).place(x='950',y='440')
        bt=tkinter.Button(rot,text='Change',command=rolechange).place(x='950',y='480')
        bt=tkinter.Button(rot,text='Change',command=phnchange).place(x='950',y='520')
        bt=tkinter.Button(rot,text='Change',command=adrschange).place(x='950',y='560')
    def deleter():
        axt=str(ae.get())
        sql=('DELETE FROM stf WHERE id='+axt)
        cus.execute(sql)
        ct.commit()
        ato=tkinter.Label(rot,text='DELETED!',fg='white',bg='black')
        ato.pack()
        ato.place(x='840',y='300')
        
        
    bt=tkinter.Button(rot,text='Show',command=alg).place(x='700',y='280')
    btt=tkinter.Button(rot,text='Edit',command=changer).place(x='745',y='280')
    bttt=tkinter.Button(rot,text='Delete',command=deleter).place(x='780',y='280')
    rot.mainloop()
    
i1=Image.open("head.jpg")
i2=Image.open("middle.jpg")
i3=Image.open("legs.jpg")
i4=Image.open("forehead.jpg")
i5=Image.open("ent.jpg")
i6=Image.open("mt.jpg")
i7=Image.open("ua.jpg")
i8=Image.open("la.jpg")
i9=Image.open("iup.jpg")
i10=Image.open("imid.jpg")
i11=Image.open("idown.jpg")
im1=ImageTk.PhotoImage(i1)
im2=ImageTk.PhotoImage(i2)
im3=ImageTk.PhotoImage(i3)
im4=ImageTk.PhotoImage(i4)
im5=ImageTk.PhotoImage(i5)
im6=ImageTk.PhotoImage(i6)
im7=ImageTk.PhotoImage(i7)
im8=ImageTk.PhotoImage(i8)
im9=ImageTk.PhotoImage(i9)
im10=ImageTk.PhotoImage(i10)
im11=ImageTk.PhotoImage(i11)

def appointment():

    rot=tkinter.Toplevel(root)
    rot.title("Staff Details")
    rot.geometry("1000x1500")
    rot.configure(bg='black')
    def exii():
        rot.destroy()
    bck=tkinter.Button(rot,text="←",bg='green',fg='white',font='100',command=exii).place(x='50',y='50')
    
    aqq=tkinter.Label(rot,text="Enter Doctor ID: ",fg='white',bg='black')
    aqq.pack()
    aqq.place(x='610',y='50')
    b=tkinter.Entry(rot)
    b.pack()
    b.place(x='700',y='50')
    bqq=tkinter.Label(rot,text="Enter Pain Area: ",fg='white',bg='black')
    bqq.pack()
    bqq.place(x='610',y='100')
    bq=tkinter.Entry(rot)
    bq.pack()
    bq.place(x='700',y='100')
    aa=tkinter.Label(rot,text="Enter Name: ",fg='white',bg='black')
    aa.pack()
    aa.place(x='620',y='150')
    bb=tkinter.Entry(rot)
    bb.pack()
    bb.place(x='700',y='150')
               
    def algo():
        bge=b.get()
        bbge=bb.get()
        be=bq.get()
        sql=("UPDATE stf SET tappt=%s WHERE id= %s")
        bbb=(bbge,bge)
        cus.execute(sql,bbb)
        sql=("UPDATE stf SET appt=%s WHERE id= %s")
        bbb=(be,bge)
        cus.execute(sql,bbb)
        ct.commit()
        bqqq=tkinter.Label(rot,text="Appointed!!!",fg='white',bg='black')
        bqqq.pack()
        bqqq.place(x='750',y='180')   
    def hpar():
        fh=tkinter.Button(rot,image=im4,bg='black').place(x='620',y='200')
        fe=tkinter.Button(rot,image=im5,bg='black').place(x='600',y='350')
        fm=tkinter.Button(rot,image=im6,bg='black').place(x='615',y='500')
    def hbod():
        upa=tkinter.Button(rot,image=im7,bg='black').place(x='550',y='220')
        lpa=tkinter.Button(rot,image=im8,bg='black').place(x='565',y='379')
    def hleg():
        iup=tkinter.Button(rot,image=im9,bg='black').place(x='650',y='220')
        imid=tkinter.Button(rot,image=im10,bg='black').place(x='650',y='555')
        idown=tkinter.Button(rot,image=im11,bg='black').place(x='653',y='666')
    but=tkinter.Button(rot,text='Appoint',bg='green',fg='white',command=algo).place(x='700',y='180')
    logo=tkinter.Label(rot,image=photo,bg='black')
    logo.pack()
    head=tkinter.Button(rot,image=im1,bg='black',command=hpar)
    head.place(x="130",y='100')
    mid=tkinter.Button(rot,image=im2,bg='black',command=hbod).place(x='0',y='220')
    leg=tkinter.Button(rot,image=im3,bg='black',command=hleg).place(x='85',y='520')
 
def exii():
    root.destroy()
    
a=tkinter.Button(root,text='Add Staff',bg='green',fg='white',bd='25',command=adstaff).place(x='150',y='400')
b=tkinter.Button(root,text='Edit Staff',bg='yellow',bd='25',command=wdata).place(x='150',y='550')
ex=tkinter.Button(root,text='Exit',bg='red',fg='white',bd='25',command=exii).place(x='450',y='700')
exa=tkinter.Button(root,text='Make Appointment',bg='white',fg='red',bd='25',command=appointment).place(x='700',y='700')


root.mainloop()

    
